### ISSUE TITLE
windows is not avalaible 

### ISSUE THREAD

**Issue by alphaleadership** [vladmandic/nanodet#1]

**Comment by vladmandic** [comment]
not sure what you mean, can you elaborate?

**Comment by vladmandic** [comment]
closing this as no description of what is the issue is provided.  
when creating an issue, please describe it in more details and also fill the appropriate issue template.

**Comment by alphaleadership** [comment]
tfjs is not acces in windows

**Comment by vladmandic** [comment]
you still did not post error message or fill the issue template. i have no idea what "tjfs is not acces in windows" means.
