### ISSUE TITLE
About the run time

### ISSUE THREAD

**Issue by ghoshaw** [vladmandic/nanodet#2]
Hi, I convert the nano-0.5x to tfjs.  it almost the same like your method.  pytorch->onnx->simplifier->savedmodel->tfjs.
But I run MNN version using cpu(pc, not that well) is only 10 ms needed, but the tfjs runs 200ms. Did you have such questions?
Thanks!

**Comment by vladmandic** [comment]
when you say `cpu`, you mean in **browser** or in **nodejs**? which `tfjs` backend?  
actual `cpu` backend is javascript implementation of kernel ops, that is always going to be terribly slow.
