### ISSUE TITLE
The prediction no good

### ISSUE THREAD

**Issue by lijianyuhoopox** [vladmandic/nanodet#3]

**Comment by lijianyuhoopox** [comment]
![image](https://user-images.githubusercontent.com/107986839/176868118-ec462066-bfde-4c11-bfc2-6ebd1324474d.png)

**Comment by vladmandic** [comment]
can you please provide the original image without labels so i can reproduce?

**Comment by vladmandic** [comment]
I took a quick look and `nanodet-t` is just that bad. using `nanodet-g` variation produces expected results, so not sure if there is anything to do here (i've updated demo to use g variation by default).
