### ISSUE TITLE
Issue with model signature

### ISSUE THREAD

**Issue by adithya1-7** [vladmandic/nanodet#4]
Please help me solve this issue
https://github.com/RangiLyu/nanodet/issues/460

**Comment by vladmandic** [comment]
`nanodet-plus` is very different than previous version of `nanodet` and it seems that all outputs layers are flattened when exporting to `onnx`.

for example, in the old `export_onnx.py`: `output_names = generate_ouput_names(config.model.arch.head)`  
and in the new `export_onnx.py`: `output_names=["output"]`  

and even in model architecture itself, it seems that its designed to return single result and the handle it in post processing

all-in-all, this is a completely different beast and would need to figure out post-processing on how to interpret results - but at the moment, i have no time or desire to do so - sorry.

**Comment by adithya1-7** [comment]
Hey. Thanks for replying. I was having this issue with `nanodet` and not `nanodet-plus`. I am only trying to replicate the conversion process from PyTorch to JS (.pth→onnx→savedmodel→json). Can you point me to the commit/tag and steps to convert pretrained PyTorch to TFJS format? When I tried with `v0.4.2`, I got the following error while running the command : `python tools/export_onnx.py --cfg_path config/nanodet-m-416.yml --model_path nanodet_m_416.pth --out_path nanodet_m_416.onnx`

Error
`RuntimeError: number of output names provided (6) exceeded number of outputs (1)`

**Comment by vladmandic** [comment]
Version of export_onnx.py must match version of the model - it has changed significantly since I did my conversion.
